export type TarotCard = {
  number: number;
  name: string;
  hebrewLetter: string;
  src: string;
};

export const tarotDeck: TarotCard[] = [
  { number: 0, name: "TheFool", hebrewLetter: "א", src: "/cards/pictorial-key-to-the-tarot-00-the-fool.jpg" },
  { number: 1, name: "TheMagician", hebrewLetter: "ב", src: "/cards/pictorial-key-to-the-tarot-01-the-magician.jpg" },
  { number: 2, name: "TheHighPriestess", hebrewLetter: "ג", src: "/cards/pictorial-key-to-the-tarot-02-the-high-priestess.jpg" },
  { number: 3, name: "TheEmpress", hebrewLetter: "ד", src: "/cards/pictorial-key-to-the-tarot-03-the-empress.jpg" },
  { number: 4, name: "TheEmperor", hebrewLetter: "ה", src: "/cards/pictorial-key-to-the-tarot-04-the-emperor.jpg" },
  { number: 5, name: "TheHierophant", hebrewLetter: "ו", src: "/cards/pictorial-key-to-the-tarot-05-the-hierophant.jpg" },
  { number: 6, name: "TheLovers", hebrewLetter: "ז", src: "/cards/pictorial-key-to-the-tarot-06-the-lovers.jpg" },
  { number: 7, name: "TheChariot", hebrewLetter: "ח", src: "/cards/pictorial-key-to-the-tarot-07-the-chariot.jpg" },
  { number: 8, name: "Strength", hebrewLetter: "ט", src: "/cards/pictorial-key-to-the-tarot-08-strength.jpg" },
  { number: 9, name: "TheHermit", hebrewLetter: "י", src: "/cards/pictorial-key-to-the-tarot-09-the-hermit.jpg" },
  { number: 10, name: "WheelOfFortune", hebrewLetter: "י", src: "/cards/pictorial-key-to-the-tarot-10-wheel-of-fortune.jpg" },
  { number: 11, name: "Justice", hebrewLetter: "י", src: "/cards/pictorial-key-to-the-tarot-11-justice.jpg" },
  { number: 12, name: "TheHangedMan", hebrewLetter: "ל", src: "/cards/pictorial-key-to-the-tarot-12-the-hanged-man.jpg" },
  { number: 13, name: "Death", hebrewLetter: "מ", src: "/cards/pictorial-key-to-the-tarot-13-death.jpg" },
  { number: 14, name: "Temperance", hebrewLetter: "נ", src: "/cards/pictorial-key-to-the-tarot-14-temperance.jpg" },
  { number: 15, name: "TheDevil", hebrewLetter: "ס", src: "/cards/pictorial-key-to-the-tarot-15-the-devil.jpg" },
  { number: 16, name: "TheTower", hebrewLetter: "ע", src: "/cards/pictorial-key-to-the-tarot-16-the-tower.jpg" },
  { number: 17, name: "TheStar", hebrewLetter: "פ", src: "/cards/pictorial-key-to-the-tarot-17-the-star.jpg" },
  { number: 18, name: "TheMoon", hebrewLetter: "צ", src: "/cards/pictorial-key-to-the-tarot-18-the-moon.jpg" },
  { number: 19, name: "TheSun", hebrewLetter: "ק", src: "/cards/pictorial-key-to-the-tarot-19-the-sun.jpg" },
  { number: 20, name: "Judgement", hebrewLetter: "ר", src: "/cards/pictorial-key-to-the-tarot-20-judgement.jpg" },
  { number: 21, name: "TheWorld", hebrewLetter: "ש", src: "/cards/pictorial-key-to-the-tarot-21-the-world.jpg" },
  { number: 22, name: "KingOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-14.jpg" },
  { number: 23, name: "QueenOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-13.jpg" },
  { number: 24, name: "KnightOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-12.jpg" },
  { number: 25, name: "PageOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-11.jpg" },
  { number: 26, name: "KingOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-14.jpg" },
  { number: 27, name: "QueenOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-13.jpg" },
  { number: 28, name: "KnightOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-12.jpg" },
  { number: 29, name: "PageOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-11.jpg" },
  { number: 30, name: "KingOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-14.jpg" },
  { number: 31, name: "QueenOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-13.jpg" },
  { number: 32, name: "KnightOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-12.jpg" },
  { number: 33, name: "PageOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-11.jpg" },
  { number: 34, name: "KingOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-14.jpg" },
  { number: 35, name: "QueenOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-13.jpg" },
  { number: 36, name: "KnightOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-12.jpg" },
  { number: 37, name: "PageOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-11.jpg" },
  { number: 38, name: "AceOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-01.jpg" },
  { number: 39, name: "TwoOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-02.jpg" },
  { number: 40, name: "ThreeOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-03.jpg" },
  { number: 41, name: "FourOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-04.jpg" },
  { number: 42, name: "FiveOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-05.jpg" },
  { number: 43, name: "SixOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-06.jpg" },
  { number: 44, name: "SevenOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-07.jpg" },
  { number: 45, name: "EightOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-08.jpg" },
  { number: 46, name: "NineOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-09.jpg" },
  { number: 47, name: "TenOfWands", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-wands-10.jpg" },
  { number: 48, name: "AceOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-01.jpg" },
  { number: 49, name: "TwoOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-02.jpg" },
  { number: 50, name: "ThreeOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-03.jpg" },
  { number: 51, name: "FourOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-04.jpg" },
  { number: 52, name: "FiveOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-05.jpg" },
  { number: 53, name: "SixOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-06.jpg" },
  { number: 54, name: "SevenOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-07.jpg" },
  { number: 55, name: "EightOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-08.jpg" },
  { number: 56, name: "NineOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-09.jpg" },
  { number: 57, name: "TenOfCups", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-cups-10.jpg" },
  { number: 58, name: "AceOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-01.jpg" },
  { number: 59, name: "TwoOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-02.jpg" },
  { number: 60, name: "ThreeOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-03.jpg" },
  { number: 61, name: "FourOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-04.jpg" },
  { number: 62, name: "FiveOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-05.jpg" },
  { number: 63, name: "SixOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-06.jpg" },
  { number: 64, name: "SevenOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-07.jpg" },
  { number: 65, name: "EightOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-08.jpg" },
  { number: 66, name: "NineOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-09.jpg" },
  { number: 67, name: "TenOfSwords", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-swords-10.jpg" },
  { number: 68, name: "AceOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-01.jpg" },
  { number: 69, name: "TwoOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-02.jpg" },
  { number: 70, name: "ThreeOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-03.jpg" },
  { number: 71, name: "FourOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-04.jpg" },
  { number: 72, name: "FiveOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-05.jpg" },
  { number: 73, name: "SixOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-06.jpg" },
  { number: 74, name: "SevenOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-07.jpg" },
  { number: 75, name: "EightOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-08.jpg" },
  { number: 76, name: "NineOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-09.jpg" },
  { number: 77, name: "TenOfPentacles", hebrewLetter: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-10.jpg" },
];