export type TarotCard = {
  id: string;
  name: string;
  number: number;
  hebrew: string;
  src: string;
};

export const tarotDeck: TarotCard[] = [
  { id: "00-the-fool", number: 0, name: "The Fool", hebrew: "א", src: "/cards/pictorial-key-to-the-tarot-00-the-fool.jpg" },
  { id: "01-the-magician", number: 1, name: "The Magician", hebrew: "ב", src: "/cards/pictorial-key-to-the-tarot-01-the-magician.jpg" },
  { id: "02-the-high-priestess", number: 2, name: "The High Priestess", hebrew: "ג", src: "/cards/pictorial-key-to-the-tarot-02-the-high-priestess.jpg" },
  { id: "03-the-empress", number: 3, name: "The Empress", hebrew: "ד", src: "/cards/pictorial-key-to-the-tarot-03-the-empress.jpg" },
  { id: "04-the-emperor", number: 4, name: "The Emperor", hebrew: "ה", src: "/cards/pictorial-key-to-the-tarot-04-the-emperor.jpg" },
  { id: "05-the-hierophant", number: 5, name: "The Hierophant", hebrew: "ו", src: "/cards/pictorial-key-to-the-tarot-05-the-hierophant.jpg" },
  { id: "06-the-lovers", number: 6, name: "The Lovers", hebrew: "ז", src: "/cards/pictorial-key-to-the-tarot-06-the-lovers.jpg" },
  { id: "07-the-chariot", number: 7, name: "The Chariot", hebrew: "ח", src: "/cards/pictorial-key-to-the-tarot-07-the-chariot.jpg" },
  { id: "08-strength", number: 8, name: "Strength", hebrew: "ט", src: "/cards/pictorial-key-to-the-tarot-08-strength.jpg" },
  { id: "09-the-hermit", number: 9, name: "The Hermit", hebrew: "י", src: "/cards/pictorial-key-to-the-tarot-09-the-hermit.jpg" },
  { id: "10-wheel-of-fortune", number: 10, name: "Wheel Of Fortune", hebrew: "י", src: "/cards/pictorial-key-to-the-tarot-10-wheel-of-fortune.jpg" },
  { id: "11-justice", number: 11, name: "Justice", hebrew: "י", src: "/cards/pictorial-key-to-the-tarot-11-justice.jpg" },
  { id: "12-the-hanged-man", number: 12, name: "The Hanged Man", hebrew: "ל", src: "/cards/pictorial-key-to-the-tarot-12-the-hanged-man.jpg" },
  { id: "13-death", number: 13, name: "Death", hebrew: "מ", src: "/cards/pictorial-key-to-the-tarot-13-death.jpg" },
  { id: "14-temperance", number: 14, name: "Temperance", hebrew: "נ", src: "/cards/pictorial-key-to-the-tarot-14-temperance.jpg" },
  { id: "15-the-devil", number: 15, name: "The Devil", hebrew: "ס", src: "/cards/pictorial-key-to-the-tarot-15-the-devil.jpg" },
  { id: "16-the-tower", number: 16, name: "The Tower", hebrew: "ע", src: "/cards/pictorial-key-to-the-tarot-16-the-tower.jpg" },
  { id: "17-the-star", number: 17, name: "The Star", hebrew: "פ", src: "/cards/pictorial-key-to-the-tarot-17-the-star.jpg" },
  { id: "18-the-moon", number: 18, name: "The Moon", hebrew: "צ", src: "/cards/pictorial-key-to-the-tarot-18-the-moon.jpg" },
  { id: "19-the-sun", number: 19, name: "The Sun", hebrew: "ק", src: "/cards/pictorial-key-to-the-tarot-19-the-sun.jpg" },
  { id: "20-judgement", number: 20, name: "Judgement", hebrew: "ר", src: "/cards/pictorial-key-to-the-tarot-20-judgement.jpg" },
  { id: "21-the-world", number: 21, name: "The World", hebrew: "ש", src: "/cards/pictorial-key-to-the-tarot-21-the-world.jpg" },
  { id: "22-ace-of-wands", number: 22, name: "Ace Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-01.jpg" },
  { id: "23-two-of-wands", number: 23, name: "Two Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-02.jpg" },
  { id: "24-three-of-wands", number: 24, name: "Three Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-03.jpg" },
  { id: "25-four-of-wands", number: 25, name: "Four Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-04.jpg" },
  { id: "26-five-of-wands", number: 26, name: "Five Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-05.jpg" },
  { id: "27-six-of-wands", number: 27, name: "Six Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-06.jpg" },
  { id: "28-seven-of-wands", number: 28, name: "Seven Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-07.jpg" },
  { id: "29-eight-of-wands", number: 29, name: "Eight Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-08.jpg" },
  { id: "30-nine-of-wands", number: 30, name: "Nine Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-09.jpg" },
  { id: "31-ten-of-wands", number: 31, name: "Ten Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-10.jpg" },
  { id: "32-page-of-wands", number: 32, name: "Page Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-11.jpg" },
  { id: "33-knight-of-wands", number: 33, name: "Knight Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-12.jpg" },
  { id: "34-queen-of-wands", number: 34, name: "Queen Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-13.jpg" },
  { id: "35-king-of-wands", number: 35, name: "King Of Wands", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-wands-14.jpg" },
  { id: "36-ace-of-cups", number: 36, name: "Ace Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-01.jpg" },
  { id: "37-two-of-cups", number: 37, name: "Two Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-02.jpg" },
  { id: "38-three-of-cups", number: 38, name: "Three Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-03.jpg" },
  { id: "39-four-of-cups", number: 39, name: "Four Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-04.jpg" },
  { id: "40-five-of-cups", number: 40, name: "Five Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-05.jpg" },
  { id: "41-six-of-cups", number: 41, name: "Six Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-06.jpg" },
  { id: "42-seven-of-cups", number: 42, name: "Seven Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-07.jpg" },
  { id: "43-eight-of-cups", number: 43, name: "Eight Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-08.jpg" },
  { id: "44-nine-of-cups", number: 44, name: "Nine Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-09.jpg" },
  { id: "45-ten-of-cups", number: 45, name: "Ten Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-10.jpg" },
  { id: "46-page-of-cups", number: 46, name: "Page Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-11.jpg" },
  { id: "47-knight-of-cups", number: 47, name: "Knight Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-12.jpg" },
  { id: "48-queen-of-cups", number: 48, name: "Queen Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-13.jpg" },
  { id: "49-king-of-cups", number: 49, name: "King Of Cups", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-cups-14.jpg" },
  { id: "50-ace-of-swords", number: 50, name: "Ace Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-01.jpg" },
  { id: "51-two-of-swords", number: 51, name: "Two Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-02.jpg" },
  { id: "52-three-of-swords", number: 52, name: "Three Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-03.jpg" },
  { id: "53-four-of-swords", number: 53, name: "Four Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-04.jpg" },
  { id: "54-five-of-swords", number: 54, name: "Five Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-05.jpg" },
  { id: "55-six-of-swords", number: 55, name: "Six Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-06.jpg" },
  { id: "56-seven-of-swords", number: 56, name: "Seven Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-07.jpg" },
  { id: "57-eight-of-swords", number: 57, name: "Eight Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-08.jpg" },
  { id: "58-nine-of-swords", number: 58, name: "Nine Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-09.jpg" },
  { id: "59-ten-of-swords", number: 59, name: "Ten Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-10.jpg" },
  { id: "60-page-of-swords", number: 60, name: "Page Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-11.jpg" },
  { id: "61-knight-of-swords", number: 61, name: "Knight Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-12.jpg" },
  { id: "62-queen-of-swords", number: 62, name: "Queen Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-13.jpg" },
  { id: "63-king-of-swords", number: 63, name: "King Of Swords", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-swords-14.jpg" },
  { id: "64-ace-of-pentacles", number: 64, name: "Ace Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-01.jpg" },
  { id: "65-two-of-pentacles", number: 65, name: "Two Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-02.jpg" },
  { id: "66-three-of-pentacles", number: 66, name: "Three Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-03.jpg" },
  { id: "67-four-of-pentacles", number: 67, name: "Four Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-04.jpg" },
  { id: "68-five-of-pentacles", number: 68, name: "Five Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-05.jpg" },
  { id: "69-six-of-pentacles", number: 69, name: "Six Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-06.jpg" },
  { id: "70-seven-of-pentacles", number: 70, name: "Seven Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-07.jpg" },
  { id: "72-eight-of-pentacles", number: 72, name: "Eight Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-08.jpg" },
  { id: "73-nine-of-pentacles", number: 73, name: "Nine Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-09.jpg" },
  { id: "74-ten-of-pentacles", number: 74, name: "Ten Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-10.jpg" },
  { id: "75-page-of-pentacles", number: 75, name: "Page Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-11.jpg" },
  { id: "76-knight-of-pentacles", number: 76, name: "Knight Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-12.jpg" },
  { id: "77-queen-of-pentacles", number: 77, name: "Queen Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-13.jpg" },
  { id: "78-king-of-pentacles", number: 78, name: "King Of Pentacles", hebrew: "", src: "/cards/pictorial-key-to-the-tarot-pentacles-14.jpg" },
];